<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ page session="true" %>
<html>
<head>
<title>PHORM: Terms & Condition</title>
<link rel="stylesheet" href="/resources/css/effect.css" />
<script src="/resources/js/terms.js"></script>
</head>
<body>
	<div class="overall">
		<div class="header">PHORM: Terms & Conditions</div>
		<div class="firstPara">
			<p>
				<ol>
						<li>This website is designed with an intention to help developers to build spring application quickly.</li>
						<li>The source code generated by this website is provided without warranty of any kind.</li>
						<li>In no event will website or website designer or website hosting company be liable for any indirect, incidental, special, punitive or
						consequential damages, or damages for loss of profits, revenue, data or data use, incurred by you or any third party, whether in an
						action in contract or tort.</li>
						<li>You understand that various cyber threats exist and data can be manipulated. You have to verify the downloaded content and need to scan the file with antivirus software.</li>
						<li>You need to add business logic to the downloaded project and fine tune it for performance.</li>
				</ol>				
			</p>
		</div>
		<%String termUrl =response.encodeURL("/phorm/termSave.do");%>
		<form action="<%=termUrl%>"
			method="post">
			<div id="terMark">
				<input type="checkbox" id="termCond" value="" onclick="addBar();" />I
				understand and agree to terms and conditions listed above.<br />
			</div>
		</form>
		<div class="firstPara">
			<ol>
				<li>Scan the downloaded file with antivirus software.</li>
				<li>Unzip the file.</li>
				<li>Edit the /src/resources/application.properties file as per your database setup.</li>
				<li>Edit the /pom.xml file to add necessary jdbc jar to build path.</li>
				<li>Import the project in your IDE.</li>
				<li>Add necessary business logic, fine tune the code for performance.</li>
				<li>You are all set to run the application.</li>
			</ol>
		</div>
		<div class="footer">&copy; 2020</div>
	</div>
</body>
</html>